### ISSUE TITLE
Julia 0.4 support

### ISSUE THREAD

**Issue by stevengj** [stevengj/Hadamard.jl#3]
After the Julia DFT API updates in JuliaLang/julia#12201, this module needs significant changes to work with 0.4.  (It is probably best to just fork a new 0.4 version.)

**Comment by macd** [comment]
Any chance of getting an update to 0.5 soon?  I'd like to use the fast hadamard for looking at dimension reduction.  Thanks.

**Comment by stevengj** [comment]
Done.  Will tag soon.

**Comment by stevengj** [comment]
Whoops, it works with 0.4, but not with 0.5 yet.

**Comment by stevengj** [comment]
Okay, 02c5b8523817fdc8e4b7408d76d0b0d9fca7d6d1 fixes it in 0.5 too.

**Comment by macd** [comment]
Works great!  Many thanks.

**Comment by stevengj** [comment]
Great, tagged as version 0.2.
